### ISSUE TITLE
存在意義

### ISSUE THREAD

**Issue by tosuke** [future-link/misskey-id#1]
misskey-authにview乗っけるんじゃだめなんですか？

**Comment by otofune** [comment]
view乗っけるのにさまざまな変更が (フォルダ構成弄るのに) 必要なのでこっちで勝手に進めてあとでそっちにマージする (RFCにしているのはそういう意味です) ってことをしたいんですね

**Comment by otofune** [comment]
なのでそっちが準備万端になればこっちからコードを移して終わりです

**Comment by tosuke** [comment]
:+1:
